### ISSUE TITLE
CC: Esolang wiki

### ISSUE THREAD

**Issue by rdebath** [ararslan/qqq-lang#2]
This language is very similar to a TrivialBrainfuckSubstitution, however, it is not Turing complete due to the loss of nested loops.

Try translating the ["Hello world" on Wikipedia](https://en.wikipedia.org/wiki/Brainfuck#Hello_World.21)

**Comment by m-ender** [comment]
I don't see why there would be any loss of nested loops. [See the Talk page on esolangs](http://esolangs.org/wiki/Talk:%3F%3F%3F).

**Comment by rdebath** [comment]
Ok, invalid issue. It's a full TBF.

```
;........",-.........;'"'-!;;.;,".'"'..;..;...";",;...--...;'"'--'"';,,,,,!;,;
...!!...!;,!--.";".;.'"';;'"'-,,,,,,,,,,,,,,!;;!...!,,,,,,!,,,,,,,,!;.!;.!

```
