### ISSUE TITLE
Inconsistent detection of mismatched brackets

### ISSUE THREAD

**Issue by ararslan** [ararslan/qqq-lang#3]
The code is supposed to begin by checking for mismatched brackets but this seems not to work consistently. An example is the following code:

```
;?"';?"."-"',-";"';";"-,"';"-!;;"--."
```

This contains `" ' " "` which is the equivalent of `[ ] ]` (in terms of Brainfuck brackets). Rather than throwing an exception as expected, the code simply enters an infinite loop.

**Comment by phase** [comment]
Is it stalling on searching for the `[` that matches the last `]`?

**Comment by BrainSteel** [comment]
Looks like this could be fixed with `if (open_quotes < 0) {break;}` immediately after the case statement in `from_stream` (line 151). I do not have time to thoroughly test this, but it seems to work as expected.
